# Header

author: ReadPond

menu:
  主页: /
  随笔: /tags/随笔/
  生活: /tags/生活
  JavaSE: /tags/javase
  大学专业: /tags/大学专业
  归档: /archives/index.html

# SubNav
subnav:
  #github: "#"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  qq: "/assets/qq.jpg"
  weixin: "/assets/wechat.jpg"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  # mail: "mailto:1102640407@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 设置字数统计显示
word_count: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
#alipay:
# 微信二维码图片地址
weixin: /assets/wechatpay.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
#favicon: /favicon.png

#你的头像url
avatar: /assets/head.jpg

#是否开启分享
share_jia: false

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: true

#2、网易云跟帖
wangyiyun: true

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

#6、Valine https://valine.js.org
valine:
 appid: 9LBg3wfntp85ryA0Q8lGYMbm-gzGzoHsz
 appkey: RkQOFJLpcOHtnasnV2HYLIpA
 verify: false #验证码，verify和notify这两个最好就别动了
 notify: false #评论回复提醒
 avatar: mm #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
 placeholder: Just go go #评论框占位符

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  enable: true
 # 头像上面的背景颜色
  header: 'rgba(0,0,0,0)' #设置背景透明，不然头像上方是默认色
 #左侧头像板块的背景颜色
  left_ground: 'url(/assets/black02.jpg)no-repeat 100%;background-size:cover;'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
# smart_menu: flase
friends: false
smart_menu:
  innerArchive: '所有文章'
  # friends: '友链'
  aboutme: '关于我'

# friends:
   # 友情链接1: https://user.qzone.qq.com/1102640407/
   # 友情链接2: http://localhost:4000/
   # 友情链接3: http://localhost:4000/
   # 友情链接4: http://localhost:4000/
   # 友情链接5: http://localhost:4000/
   # 友情链接6: http://localhost:4000/

music:
  enable: true
  id: 4968396  # 网易云分享的ID,ID可以随时替换
  autoplay: true  # 是否开启自动播放

aboutme: 中二<br>内向<br>喜欢研究代码但是不会以此为工作<br>专心自驾<br>欢迎Email：1102640407@qq.com

# 版权声明
#在需要进行版权声明的文章的md文件头部，设置属性declare: true。
#版权基础设定：0-关闭声明； 1-文章对应的md文件里有declare: true属性，才有版权声明； 2-所有文章均有版权声明
declare_type: 2
licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/        #当前应用的版权协议地址。
licensee_name: '知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议'        #版权协议的名称
licensee_img: https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png    #版权协议的Logo
